### ISSUE TITLE
Support for AbortController

### ISSUE THREAD

**Issue by gracicot** [phytonmk/react-use-await#2]
It can happen that a component gets unmounted before a request is done. In such case, it's usually a good practice to use an abort controller. It also helps handling cancelled requests in a graceful way.

Is there a plan to support cancellation? Or is there a way to add cancellation into a request in a way that would work with this library? Thanks for the response.

**Comment by msereniti** [comment]
Hi Guillaume,

Thank you for your interest in the package. The package provides a wrapper for data fetchers and has no concerns about their lifecycle. You can use the `AbortController` API as you would in any other JS application. It is important to note, however, that the component with `useAwait` is not mounted until the end of data fetching, so the component unmount event should be handled on the `<AwaitBoundary>...<AwaitBoundary />` level.

Short example:

```javascript
import { useAwait, AwaitBoundary } from 'react-use-await';

const getCurrency = async (id, fetchOptions) => await fetch(`http://sereniti.tech/static/${id}.json`, fetchOptions).then((res) => res.json());

const abortController = new AbortController();
const CurrencyView = ({ id }) => {
  const price = useAwait(getCurrency, id, { signal: abortController.signal });

  return (
    <div>
      {id}: {price}
    </div>
  );
};

export const App = () => {
  React.useEffect(() => {
    return () => abortController.abort();
  }, []);

  return (
    <AwaitBoundary loading="loading" ErrorView={({ error }) => error.message}>
      <CurrencyView id="stonks" />
    </AwaitBoundary>
  );
};
```

I should also note that in React strict mode, useEffect may be called multiple times, so aborting data fetching on component unmount may not work as you may expect.

Believe I have fully answered your question, so this issue is going to be closed. If you have any other doubts or questions, feel free to reopen the issue or create a new one. 😉

**Comment by gracicot** [comment]
Hmm, I guess I will have to create my own hook to automate this, it's 100% in reach and the example really helps, thank you. I was still hoping an abort controller could be put in the context of `AwaitBoundary` and sent to the async function, but I understand it might not be trivial, and potentially breaking change to do so.
